# Generated by Django 4.1 on 2022-08-30 15:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Автоматически задается при создании', verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, help_text='Автоматически задается при каждом изменении', verbose_name='Дата и время изменения')),
                ('name', models.CharField(help_text='Наименование ингредиента', max_length=200, verbose_name='Ингредиент')),
                ('measurement_unit', models.CharField(help_text='Единица измерения ингредиента', max_length=200, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ['name'],
                'unique_together': {('name', 'measurement_unit')},
            },
        ),
        migrations.CreateModel(
            name='IngredientAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(help_text='Количество ингредиента в рецепте', validators=[django.core.validators.MinValueValidator(1, 'В рецепте должен быть хотя бы 1 ингредиент'), django.core.validators.MaxValueValidator(5000, 'В рецепте не может быть более 5000 ингредиентов')], verbose_name='Количество')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.ingredient', verbose_name='Ингредиент')),
            ],
            options={
                'verbose_name': 'Ингредиент в рецепте',
                'verbose_name_plural': 'Ингредиенты в рецепте',
                'ordering': ['recipe'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Автоматически задается при создании', verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, help_text='Автоматически задается при каждом изменении', verbose_name='Дата и время изменения')),
                ('name', models.CharField(help_text='Наименование тега', max_length=200, unique=True, verbose_name='Тег')),
                ('color', models.CharField(default=None, help_text='Цвет тега в HEX-формате (напр. #000000 - Черный)', max_length=7, null=True, verbose_name='Цвет')),
                ('slug', models.SlugField(help_text='Уникальный адрес тега', max_length=200, unique=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Автоматически задается при создании', verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, help_text='Автоматически задается при каждом изменении', verbose_name='Дата и время изменения')),
                ('name', models.CharField(help_text='Наименование рецепта', max_length=200, verbose_name='Рецепт')),
                ('text', models.TextField(help_text='Описание рецепта', verbose_name='Описание')),
                ('image', models.ImageField(upload_to='recipes/', verbose_name='Изображение')),
                ('cooking_time', models.PositiveSmallIntegerField(help_text='Время приготовления рецепта в минутах', validators=[django.core.validators.MinValueValidator(1, 'Время приготовления не может быть меньшеминуты'), django.core.validators.MaxValueValidator(1440, 'Время приготовления не может быть больше24 часов')], verbose_name='Время приготовления')),
                ('author', models.ForeignKey(help_text='Автор рецепта', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('cart', models.ManyToManyField(help_text='Список пользователей, у кого рецепт в списке покупок', related_name='user_cart', to=settings.AUTH_USER_MODEL, verbose_name='Список покупок')),
                ('favorite', models.ManyToManyField(help_text='Список пользователей, у кого рецепт в избранном', related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Избранное')),
                ('ingredients', models.ManyToManyField(help_text='Список ингредиентов рецепта', related_name='recipes', through='recipes.IngredientAmount', to='recipes.ingredient', verbose_name='Ингредиенты')),
                ('tags', models.ManyToManyField(help_text='Список тегов рецепта', related_name='recipes', to='recipes.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ['-created'],
                'unique_together': {('name', 'author')},
            },
        ),
        migrations.AddField(
            model_name='ingredientamount',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredientamount',
            unique_together={('ingredient', 'recipe')},
        ),
    ]
